final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from crews import views
from django.conf import settings  # new
from django.conf.urls.static import static  # new

urlpatterns = [
    path('admin/', admin.site.urls),

    path('crews/', views.crews),
    path('crews/<int:crew_id>/', views.crew),
    path('crews/add/', views.formulaireCreationCrew),
    path('crews/create/', views.creerCrew),
    path('crews/<int:crew_id>/addIsland/', views.ajouterIslandAuCrew),
    path('crews/<int:crew_id>/delete/', views.supprimerCrew),
    path('crews/<int:crew_id>/update/', views.formulaireModificationCrew),
    path('crews/<int:crew_id>/updated/', views.modifierCrew),
    path('crews/<int:crew_id>/deleteIsland/<int:has_id>/', views.supprimerIslandForCrew),

    path('islands/', views.islands),
    path('islands/<int:island_id>/', views.island),
    path('islands/add/', views.formulaireCreationIsland),
    path('islands/create/', views.creerIsland),
    path('islands/<int:island_id>/delete/', views.supprimerIsland),
    path('islands/<int:island_id>/update/', views.formulaireModificationIsland),
    path('islands/<int:island_id>/updated/', views.modifierIsland),

    path('regions/', views.regions),
    path('regions/<int:region_id>/', views.region),
    path('regions/<int:region_id>/delete/', views.supprimerRegion),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/crews/models.py
from django.db import models

# Create your models here.
class Crew(models.Model):
    crew_id = models.AutoField(primary_key = True)
    crew_name = models.CharField(max_length = 50, verbose_name = "crew's name ")
    crew_pic = models.ImageField(upload_to = 'images/crew/')

    def __str__(self) -> str:
        return 'Crew ' + self.crew_name

class Region(models.Model):
    region_id = models.AutoField(primary_key = True)
    region_name = models.CharField(max_length = 50, verbose_name = "region's name ")
    region_pic = models.ImageField(upload_to = 'images/region/')

    def __str__(self) -> str:
        return 'Region ' + self.region_name

class Island(models.Model):
    island_id = models.AutoField(primary_key = True)
    island_name = models.CharField(max_length = 50, verbose_name = "island's name ")
    island_region = models.ForeignKey(Region, on_delete=models.CASCADE)
    island_pic = models.ImageField(upload_to = 'images/island/')

    def __str__(self) -> str:
        return 'Island ' + self.island_name

class Has(models.Model):
    class Meta :
        unique_together = ('crew', 'island')

    has_id = models.AutoField(primary_key = True)
    crew = models.ForeignKey(Crew, on_delete = models.CASCADE)
    island = models.ForeignKey(Island, on_delete = models.CASCADE)

    def __str__(self) -> str :
        cre = self.crew
        tre = self.island
        return cre.__str__() +  ' has seen ' + tre.__str__()

final_project/crews/forms.py
from django import forms
from django.forms import ModelForm
from crews.models import Crew, Island, Has

class CrewForm(ModelForm):
    class Meta:
        model = Crew
        fields = ['crew_name', 'crew_pic']

class IslandForm(ModelForm):
    class Meta:
        model = Island
        fields = ['island_name', 'island_region', 'island_pic']

class HasForm(ModelForm):
    class Meta:
        model = Has
        fields = ['island']

final_project/crews/views.py
from django.shortcuts import render
from crews.models import Crew, Island, Has, Region
from crews.forms import CrewForm, IslandForm, HasForm

def crews(request):

    all_crews = Crew.objects.all()
    return render(
        request,
        "crews/crews.html",
        {"crews" : all_crews}
    )


def crew(request, crew_id):

    formulaire = HasForm()

    the_crew = Crew.objects.get(crew_id = crew_id)
    has = Has.objects.filter(crew_id = crew_id)
    island_list = []
    for h in has:
        island = Island.objects.get(island_id=h.island.island_id)
        island_list.append({"name": island.island_name,
                                 "pic": island.island_pic,
                                 "id": island.island_id,
                                 "has_id": h.has_id})

    return render(
        request,
        "crews/crew.html",
        {"crew" : the_crew, "island_list" : island_list, "formulaire": formulaire}
    )

def formulaireCreationCrew(request):

    formulaire = CrewForm()

    return render(
        request,
        "crews/formulaireCreationCrew.html",
        {"form": formulaire}
    )

def creerCrew(request):

    form = CrewForm(request.POST, request.FILES)
    if form.is_valid():
        crew_name = form.cleaned_data['crew_name']
        crew_pic = form.cleaned_data['crew_pic']
        crew = Crew()
        crew.crew_name = crew_name
        crew.crew_pic = crew_pic
        crew.save()
    else:
        form = CrewForm()

    return render(
        request,
        "crews/createCrew.html",
        {"crew_name": crew_name, "form" : form}
    )

def ajouterIslandAuCrew(request, crew_id):
    formulaire = HasForm(request.POST)
    if formulaire.is_valid():
        island = formulaire.cleaned_data['island']

        try:
            Has.objects.get(island_id = island.island_id, crew_id = crew_id)
        except Has.DoesNotExist:
            has = Has()
            has.crew = Crew.objects.get(crew_id = crew_id)
            has.island = Island.objects.get(island_id = island.island_id)
            has.save()

    formulaire = HasForm()
    the_crew = Crew.objects.get(crew_id = crew_id)
    has = Has.objects.filter(crew_id = crew_id)
    island_list = []
    for h in has:
        island = Island.objects.get(island_id=h.island.island_id)
        island_list.append({"name": island.island_name,
                                 "pic": island.island_pic,
                                 "id": island.island_id,
                                 "has_id": h.has_id})
    return render(request,
        "crews/crew.html",
        {"crew" : the_crew,
         "island_list" : island_list,
          "formulaire": formulaire}
        )

def supprimerCrew(request, crew_id):

    crew = Crew.objects.get(crew_id = crew_id)
    crew.delete()
    all_crews = Crew.objects.all()
    return render(
        request,
        "crews/crews.html",
        {"crews" : all_crews}
    )

def formulaireModificationCrew(request, crew_id):

    crew = Crew.objects.get(crew_id = crew_id)
    formulaire = CrewForm(instance = crew)
    return render(
        request,
        "crews/formulaireModificationCrew.html",
        {'form': formulaire, 'crew': crew}
    )

def modifierCrew(request, crew_id):
    crew = Crew.objects.get(crew_id = crew_id)
    formulaire = CrewForm(request.POST, request.FILES, instance = crew)
    if formulaire.is_valid():
        formulaire.save()
        crew = Crew.objects.get(crew_id = crew_id)
    return render(
        request,
        "crews/traitementFormulaireModificationCrew.html",
        {'crew': crew}
    )

def supprimerIslandForCrew(request, crew_id, has_id):

    formulaire = HasForm()

    has = Has.objects.filter(has_id = has_id)
    has.delete()

    the_crew = Crew.objects.get(crew_id = crew_id)
    has = Has.objects.filter(crew_id = crew_id)
    island_list = []
    for h in has:
        island = Island.objects.get(island_id=h.island.island_id)
        island_list.append({"name": island.island_name,
                                 "pic": island.island_pic,
                                 "id": island.island_id,
                                 "has_id": h.has_id})

    return render(
        request,
        "crews/crew.html",
        {"crew" : the_crew, "island_list" : island_list, "formulaire": formulaire}
    )



















def island(request, island_id):

    island = Island.objects.get(island_id = island_id)
    region = Region.objects.get(region_id = island.island_region.region_id)
    return render(
        request,
        "crews/island.html",
        {"island" : island, "region" : region}
    )


def islands(request):

    all_islands = Island.objects.all()

    return render(
        request,
        "crews/islands.html",
        {"islands" : all_islands}
    )

def formulaireCreationIsland(request):

    formulaire = IslandForm()

    return render(
        request,
        "crews/formulaireCreationIsland.html",
        {"form": formulaire}
    )

def creerIsland(request):

    form = IslandForm(request.POST, request.FILES)
    if form.is_valid():
        island_name = form.cleaned_data['island_name']
        island_region = form.cleaned_data['island_region']
        island_pic = form.cleaned_data['island_pic']
        region_id = form.cleaned_data['island_region']
        island = Island()
        island.island_name = island_name
        island.island_region = island_region
        island.island_pic = island_pic
        island.island_region = region_id
        island.save()
    else:
        form = IslandForm()

    return render(
        request,
        "crews/createIsland.html",
        {"island_name": island_name, "form" : form}
    )

def supprimerIsland(request, island_id):

    island = Island.objects.get(island_id = island_id)
    island.delete()
    all_islands = Island.objects.all()
    return render(
        request,
        "crews/islands.html",
        {"islands" : all_islands}
    )

def formulaireModificationIsland(request, island_id):

    island = Island.objects.get(island_id = island_id)
    formulaire = IslandForm(instance = island)
    return render(
        request,
        "crews/formulaireModificationIsland.html",
        {'form': formulaire, 'island': island}
    )

def modifierIsland(request, island_id):
    island = Island.objects.get(island_id = island_id)
    formulaire = IslandForm(request.POST, request.FILES, instance = island)
    if formulaire.is_valid():
        formulaire.save()
        island = Island.objects.get(island_id = island_id)
    return render(
        request,
        "crews/traitementFormulaireModificationIsland.html",
        {'island': island}
    )










def region(request, region_id):

    formulaire = HasForm()

    region = Region.objects.get(region_id = region_id)
    part = Island.objects.filter(island_region = region_id)
    island_list = []
    for p in part:
        island = Island.objects.get(island_id=p.island_id)
        island_list.append({"name": island.island_name,
                                 "pic": island.island_pic,
                                 "id": island.island_id})

    return render(
        request,
        "crews/region.html",
        {"region" : region, "island_list" : island_list, "formulaire": formulaire}
    )

def regions(request):

    regions = Region.objects.all()

    return render(
        request,
        "crews/regions.html",
        {"regions" : regions}
    )

def supprimerRegion(request, region_id):
    region = Region.objects.get(region_id = region_id)
    region.delete()
    return render(
        request,
        "crews/regions.html",
        {'regions': regions}
    )

final_project/crews/templates/crews/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'crews/css/styles.css' %}">
    <link rel="icon" href="{% static 'crews/img/mugiwara.png' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<style>
    a{
        font-size: 20px;
    }
</style>
<body style="background-image: url('{% static 'crews/img/bg.png' %}'); background-size: cover;" onload="load()">
<header>
    <nav style="height: 50px; align-items: center;">
        <div><a href="/crews/" class="top_link">All crews</a></div>
        <div><a href="/islands/" class="top_link">All islands</a></div>
        <div><a href="/regions/" class="top_link">All regions</a></div>
    </nav>
</header>
<main>
    {% block content %}{% endblock %}
</main>
<footer>
    Crewsures 2023
</footer>
</body>
</html>

final_project/crews/templates/crews/createCrew.html
{% extends 'crews/base.html' %}

{% block title %}
Created crew
{% endblock %}

{% block content %}
<h2>Created crew</h2>
<p>The {{ crew_name }} has been created</p>
{% endblock %}

final_project/crews/templates/crews/createIsland.html
{% extends 'crews/base.html' %}

{% block title %}
Created island
{% endblock %}

{% block content %}
<h2>Created island</h2>
<p>The {{ island_name }} has been created</p>
{% endblock %}

final_project/crews/templates/crews/crew.html
{% extends 'crews/base.html' %}{% block title %}Crew's details{% endblock %}{% load static %}{% block content %}
<div style="display: flex; justify-content: space-between;">
    <div></div>
    <p class="title_name">{{ crew }}</p>
    <div style="display: flex; flex-direction: row; align-items: center;">
        <a href="/crews/{{crew.crew_id}}/update/">
            <div class="button" style="background-image: url('{% static 'crews/img/modify.png' %}')"></div>
        </a> <a href="/crews/{{crew.crew_id}}/delete/">
        <div class="button" style="background-image: url('{% static 'crews/img/delete.png' %}');"></div>
    </a>
    </div>
</div>
<form action="/crews/{{crew.crew_id}}/addIsland/" method="post">
    <div style="display: flex; flex-direction: row; align-items: center; justify-content: space-around; width: 260px;">
        {% csrf_token %} {{ formulaire.as_div }} <input type="submit"
                                                        style="background: url('{% static 'crews/img/add.png' %}');background-size: cover;background-position: center center;"
                                                        value="" class="adding_island_button">
    </div>
</form>
<div class="list_elements">
    {% for island in island_list %}
    <div>
        <a href="/crews/{{ crew.crew_id }}/deleteIsland/{{ island.has_id }}/">
            <div class="cross">
                X
            </div>
        </a>
        <a href="/islands/{{island.id}}" style="margin: 0 30px; width: 150px;background-image: url('{{ island.pic.url }}'); display: flex; flex-direction: row;" class="block"></a>
        <div style="color: black; display: flex; justify-content: center; word-break: break-word; text-align: center;">
            {{ island.name }}
        </div>
    </div>
    {% endfor %}
</div>{% endblock %}

final_project/crews/templates/crews/crews.html
{% extends 'crews/base.html' %}{% block title %}Crews{% endblock %}
{% load static %}
{% block content %}
<h2 class="title">All Crews</h2>
<div class="list_elements">
    <a href="/crews/add/" class="bulle">
        <div class="block" style="background-image: url('{% static 'crews/img/add.png' %}')"></div>
    </a>
    {% for crew in crews %}
    <a href="/crews/{{crew.crew_id}}" class="bulle">
        <div class="block" style="background-image: url('{{ crew.crew_pic.url }}')"></div>
        <div class="legend">{{ crew.crew_name }}</div>
    </a>
    {% endfor %}
</div>{% endblock %}

final_project/crews/templates/crews/formulaireCreationCrew.html
{% extends 'crews/base.html' %}
{% block title %}Creating crew{% endblock %}
{% load static %}
{% block content %}

<style>
  .file_upload{
    position: relative;
    top: -20px;
    right: -70px;
    background: url('{% static 'crews/img/upload.png' %}');
    background-size: cover;
    background-position: center center;
  }
</style>

<h2>Creating crew</h2>
<form action="/crews/create/" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_div }}
  <label for="id_crew_pic" class="file_upload"></label>
  <input type="submit" value="Create my crew">
</form>

<script>
  function load() {
    input = document.getElementById("id_crew_pic");
    input.style.visibility = "hidden";
    input.value = "";
  }
</script>

{% endblock %}

final_project/crews/templates/crews/formulaireCreationIsland.html
{% extends 'crews/base.html' %}
{% block title %}Creating island{% endblock %}
{% load static %}
{% block content %}

<style>
  .file_upload{
    position: relative;
    top: -20px;
    right: -70px;
    background: url('{% static 'crews/img/upload.png' %}');
    background-size: cover;
    background-position: center center;
  }
</style>

<h2>Creating island</h2>
<form action="/islands/create/" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_div }}
  <label for="id_island_pic" class="file_upload"></label>
  <input type="submit" value="Create my island">
</form>

<script>
  function load() {
    input = document.getElementById("id_island_pic");
    input.style.visibility = "hidden";
    input.value = "";
  }
</script>

{% endblock %}

final_project/crews/templates/crews/formulaireModificationCrew.html
{% extends 'crews/base.html' %}
{% block title %}
Crew modification
{% endblock %}
{% load static %}
{% block content %}

<style>
    a{
        color: black;
    }

    .file_upload{
        position: relative;
        top: -20px;
        right: -60px;
        background: url('{% static 'crews/img/upload.png' %}');
        background-size: cover;
        background-position: center center;
    }
</style>

<h2>Crew modification</h2>
<form action="/crews/{{crew.crew_id}}/updated/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <label for="id_crew_pic" class="file_upload"></label>
    <input type="submit" value="Modificate my crew">
</form>

<script>
    function load() {
        input = document.getElementById("id_crew_pic");
        input.style.visibility = "hidden";
        input.value = "";
    }
</script>

{% endblock %}

final_project/crews/templates/crews/formulaireModificationIsland.html
{% extends 'crews/base.html' %}
{% block title %}
Island modification
{% endblock %}
{% load static %}
{% block content %}

<style>
    a{
        color: black;
    }

    .file_upload{
        position: relative;
        top: -20px;
        right: -60px;
        background: url('{% static 'crews/img/upload.png' %}');
        background-size: cover;
        background-position: center center;
    }
</style>

<h2>Island modification</h2>
<form action="/islands/{{island.island_id}}/updated/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <label for="id_island_pic" class="file_upload"></label>
    <input type="submit" value="Modificate my island" style="margin-top: -5px;">
</form>

<script>
    function load() {
        console.log("coucou");
        input = document.getElementById("id_island_pic");
        input.style.visibility = "hidden";
        input.value = "";
    }
</script>

{% endblock %}

final_project/crews/templates/crews/island.html
{% extends 'crews/base.html' %}
{% block title %}Island's details{% endblock %}
{% load static %}
{% block content %}
<div style="display: flex; justify-content: space-between;">
    <div></div>
    <p class="title_name">{{ island }}</p>
    <div style="display: flex; flex-direction: row;">
        <a href="/islands/{{island.island_id}}/update/">
            <div class="button" style="background-image: url('{% static 'crews/img/modify.png' %}')"></div>
        </a>
        <a href="/islands/{{island.island_id}}/delete/">
            <div class="button" style="background-image: url('{% static 'crews/img/delete.png' %}');"></div>
        </a>
    </div>
</div>
<div style="display: flex; flex-direction: column; width: 200px; justify-content: left;">
    <a href="/regions/{{region.region_id}}/" style="margin: 0 30px; width: 150px;background-image: url('{{ region.region_pic.url }}'); display: flex; flex-direction: row;" class="block"></a>
    <div style="color: black; word-break: break-word; text-align: center;">
        {{ region.region_name }}
    </div>
</div>
{% endblock %}

final_project/crews/templates/crews/islands.html
{% extends 'crews/base.html' %}{% block title %}Islands{% endblock %}{% load static %}
{% block content %}<h2 class="title">All Islands</h2>
<div class="list_elements">
    <a href="/islands/add/" class="bulle">
        <div class="block" style="background-image: url('{% static 'crews/img/add.png' %}')"></div>
    </a>
    {% for island in islands %}
    <a href="/islands/{{island.island_id}}" style="margin: 0 50px; width: 150px;">
    <div class="block" style="background-image: url('{{ island.island_pic.url }}')"></div>
    <div style="color: black; display: flex; justify-content: center; word-break: break-word; text-align: center;">
        {{ island.island_name }}
    </div>
</a> {% endfor %}
</div>{% endblock %}

final_project/crews/templates/crews/region.html
{% extends 'crews/base.html' %}{% block title %}Region's details{% endblock %}{% load static %}{% block content %}
<div style="display: flex; justify-content: center;">
    <p class="title_name">{{ region }}</p>
</div>
<div class="list_elements">
    {% for island in island_list %}
    <div>
        <a href="/islands/{{island.id}}" style="margin: 0 30px; width: 150px;background-image: url('{{ island.pic.url }}'); display: flex; flex-direction: row;" class="block"></a>
        <div style="color: black; display: flex; justify-content: center; word-break: break-word; text-align: center;">
            {{ island.name }}
        </div>
    </div>
    {% endfor %}
</div>{% endblock %}

final_project/crews/templates/crews/regions.html
{% extends 'crews/base.html' %}{% block title %}Regions{% endblock %}{% load static %}
{% block content %}<h2 class="title">All Regions</h2>
<div class="list_elements">
    {% for region in regions %}
    <a href="/regions/{{region.region_id}}" style="margin: 0 50px; width: 150px;">
        <div class="block" style="background-image: url('{{ region.region_pic.url }}')"></div>
        <div style="color: black; display: flex; justify-content: center; word-break: break-word; text-align: center;">
            {{ region.region_name }}
        </div>
    </a> {% endfor %}
</div>{% endblock %}

final_project/crews/templates/crews/traitementFormulaireModificationIsland.html
{% extends 'crews/base.html' %}

{% block title %}
Modificated island
{% endblock %}

{% block content %}
<h2>Modificated island</h2>
<p>The {{ island.island_name }} has been modificated</p>
{% endblock %}